spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
    url: jdbc:h2:mem:database
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  kafka:
    topic: "task_updated"
    bootstrap-servers: "localhost:9092"
    group-id: "task"
    max-poll-records: 2


